### ISSUE TITLE
Is Linux support planned?

### ISSUE THREAD

**Issue by LegendaryB** [sbarrac1/Inputshare#9]
Hey,

just wanted to ask if you want to support linux in the future. Or is that not part of the goal?

Kind Regards,
Daniel

**Comment by sbarrac1** [comment]
Hi, 

Linux support is definitely planned. I did actually write a basic Linux client before that worked OK, so i'll be looking into a full Linux implementation soon.

**Comment by LegendaryB** [comment]
Do you accept help? (Pull-Requests etc.)

**Comment by sbarrac1** [comment]
Sure, I'm happy for anyone to help out.
